## TensorFlow

This example serves as a beginner's example on how to use Tensorflow to perform Matrix-Matrix multiplication. 

In [8]:
import tensorflow as tf

In [9]:
# Matrix A (2 by 3)
# A = [1 2 3
#      4 5 6]
A = tf.constant([[1., 2., 3.],[4., 5., 6.]])

# Matrix B (3 by 1)
# A = [0
#      2
#      4]
B = tf.constant([[0.],[2.],[4]])

In [10]:
# Create a Matmul operator that takes A and B as inputs, multiplies them 
# Note that product_op is the operator and not the actual matrix
product_op = tf.matmul(A, B)

In [20]:
# Now, we have to lauch a session. We can use the default session: 
sess = tf.Session()

# Let's print the values of input matrices A and B
print('Matrix A is:')
print(sess.run(A))

print('\nMatrix B is:')
print(sess.run(B))

# We can run the session with the predefined operator product_op (product of matrix A*B). 
# Tensorflow does the initialization on matrix A and B automatically
# The result is stored in R
R = sess.run(product_op)

# output R
print('\nA*B is equal to:')
print(R)

# close the session now
sess.close()

Matrix A is:
[[ 1.  2.  3.]
 [ 4.  5.  6.]]

Matrix B is:
[[ 0.]
 [ 2.]
 [ 4.]]

A*B is equal to:
[[ 16.]
 [ 34.]]
